version: "3.9"
services:
  web:
    build: .
    ports:
      - target: 5000
        published: 5000
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
